#!/bin/bash

usuario="${USER}"
senha="${PASSWORD}"

apt update 
apt -y install apache2 apache2-utils 
systemctl enable apache2 
systemctl start apache2  
apt -y install mysql-client
apt-get install php7.2 php7.2-mysql libapache2-mod-php7.2 php7.2-cli php7.2-cgi php7.2-gd php-curl -y
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
chmod +x wp-cli.phar
sudo mv wp-cli.phar /usr/local/bin/wp
cd /var/www/html/
rm -rf /var/www/html/index.html
wp core download --allow-root
wp core config --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=$IP_PRIVATE_BD --dbprefix=wp_ --allow-root
wp core install --title="Raviel" --admin_user="$usuario" --admin_password="$senha" --admin_email="your@email.com" --allow-root
#aux=`grep -n '$weblog_title[[:blank:]]*=' /var/www/html/wordpress/wp-admin/install.php | cut -f 1 -d ":"`
#n=`echo $aux | cut -f 2 -d " "`
#sed -i ""$n"s/: '';/: 'Raviel';/" /var/www/html/wordpress/wp-admin/install.php
#aux=`grep -n '$user_name[[:blank:]]*=' /var/www/html/wordpress/wp-admin/install.php | cut -f 1 -d ":"`
#n=`echo $aux | cut -f 2 -d " "`
#sed -i ""$n"s/: '';/: '"$usuario"';/" /var/www/html/wordpress/wp-admin/install.php
#n=`grep -n '$admin_password[[:blank:]]*=' /var/www/html/wordpress/wp-admin/install.php | cut -f 1 -d :`
#sed -i ""$n"s/: '';/: '"$senha"';/" /var/www/html/wordpress/wp-admin/install.php
#n=`grep -n '$admin_password_check[[:blank:]]*=' /var/www/html/wordpress/wp-admin/install.php | cut -f 1 -d :`
#sed -i ""$n"s/: '';/: '"$senha"';/" /var/www/html/wordpress/wp-admin/install.php
#aux=`grep -n '$admin_email[[:blank:]]*=' /var/www/html/wordpress/wp-admin/install.php | cut -f 1 -d ":"`
#n=`echo $aux | cut -f 2 -d " "`
#sed -i ""$n"s/: '';/: 'admin@email.com';/" /var/www/html/wordpress/wp-admin/install.php


service apache2 restart



